--- #YAML:1.0
name:                Mixin-ExtraFields-Param
version:             0.011
abstract:            make your class provide a familiar "param" method
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Mixin::ExtraFields:            0.002
    Sub::Exporter:                 0.9
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
